# Generated by Django 3.0.8 on 2021-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='accomplishments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
