# Generated by Django 3.0.8 on 2021-08-17 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210817_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='accomplishments',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Optional', max_length=200),
            preserve_default=False,
        ),
    ]
