# Generated by Django 3.0.8 on 2021-08-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210817_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='accomplishments',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True),
        ),
    ]
